### ISSUE TITLE
Fire HD tablet - FireOS

### ISSUE THREAD

**Issue by phakeEHS** [aschober/vinyl-cast#10]
Massively dumb question - but I want to re-purpose one of my Fire HD tablets as a Vinyl-Cast machine. I'm getting a parsing error when installing the apk on a Fire HD 8 (Fire OS 5.6.4.0) and also a Fire HD 7 with Android 5.1.1. What's the minimum Android requirements for the 1.0.0 release?

**Comment by rotaryrkt** [comment]
I'm getting the same issue with an old Samsung tablet.  The app loads, but crashes when you hit play.

**Comment by aschober** [comment]
@phakeEHS Never a dumb question :)

v1.0.0 supports Android 6.0+ (API Level 23) and v1.1.0 which was just posted supports Android 7.1+ (API Level 25). I went and added a comment in the README about minimum Android version needed.

 I'm not able to easily test on earlier Android versions and given my experience working with the Android audio APIs, I don't want to enable support for earlier versions without testing. But if you're still interested, I could make an app build that targets earlier Android versions and you could test it out.

**Comment by aschober** [comment]
Note that as of v1.2.0, the minimum Android level was changed back to Android 6.0 (API Level 23).

Closing issue for now due to inactivity and can reopen if necessary.
