### ISSUE TITLE
No audio from App - Turntable with USB output

### ISSUE THREAD

**Issue by Sidelobe** [aschober/vinyl-cast#15]
First of all, thanks you Allen for all the time you've invested in this great project!
 
I can't get it to work, but I feel I'm very close - maybe somebody has a hint that can help me.

I'm using a LG G4 (LineageOS 15.1, Android 8.1). OTG mode seems to work fine - I can connect and use a mouse and an USB stick. Vinyl-Cast recognizes my turntable (Teac TN300) as a USB device. I can connect to my Chromecast Audio at home and hear the chord sound through my speaker. But when I activate Vinyl-Cast, no audio arrives comes out my chromecast device.

When I select the phone's speaker as output device, I don't hear anything, so most likely Vinyl-Cast is not receiving proper audio from the USB device.  I remember seing something like 48kHz sampling rate in the settings menu, so some sort of audio stream is received by the app.

Anybody has experience in connecting a turntable with USB output?

**Comment by aschober** [comment]
@Sidelobe appreciate you checking out the project!

As one way to debug where issue lies, can you check if the background of the main UI in Vinyl Cast is moving when you're all connected and playing audio? When Vinyl Cast app is "playing", the grey bars should move up/down with the audio being recorded (like a graphic equalizer). If the grey bars are not moving a lot, then the Vinyl Cast app is not recording the audio stream as expected. Also if you select a 'Local Playback Device' then you should hear audio being recorded being played back on your LG G4.

Couple other ideas --
- Try enabling or disabling the `Low Latency Playback` option and see if that changes behavior?
- Do you have another audio device like a USB microphone or headset you can attach to your LG G4 to test with? Do you have another app on your phone to record audio? Or try attaching the Teac TN300 to a computer and seeing if you get audio as expected?
- Looks like the Teac TN300 has a built-in Phono Pre-amp controlled via a toggle switch -- not sure if that should be in the "on" position?

Annoyingly, the performance of the native audio APIs on Android can vary significantly between Android devices; lots of details are left up to device manufacturer to implement and they are not all the same so problems occurring on certain devices and Android versions are the most common issue.

Post an update if you learn anything more and I can try to help a bit more.

**Comment by Sidelobe** [comment]
Thank you for your tips, Allen!

I methodically went through everything on your list — it turns out the “low latency playback” does the trick!!
I’m listening to my vinyls on my balcony right now 🤗🤗

My android phone is somehow not charging, but that’s most likely due to the OTG adapter. I’ll order another one to test, but for now, it works fine

Thanks for your help - and thanks again for developing this and for sharing!
