### ISSUE TITLE
App Crashes

### ISSUE THREAD

**Issue by grainsoflight** [aschober/vinyl-cast#2]
App Crashes frequently on Galaxy S7 running android 7. Occasionally crashes after cast connection, always crashes after pressing the vinyl record icon to start stream

**Comment by sophschneider** [comment]
same happens to me with a pixel 2 xl

**Comment by xenokira** [comment]
Also seeing crashes on my Pixel 2 XL and Vizio XR6P (Android 6.0.1) after connecting to my cast device. Admittedly, I don't have the USB sound card yet--not sure if the crashes could be related to the expected device not being present. Already have the UFO202 on order, we'll see if makes any difference.

**Comment by dagthomas** [comment]
Crashes on all mobiles I have tested. S3, S6, Pixel 2 :(

**Comment by aschober** [comment]
I refactored the app to use better/faster/stronger native audio APIs using the Android Oboe library. Performance seems much improved on the different devices I'm able to test on (Pixel 3, Nexus 6, Nexus 5C) and no more crashes as I removed the Audio ACR library that was often causing trouble.

Check out v1.0.0 in the Releases section and re-open an issue if you're still seeing problems.
