### ISSUE TITLE
Silence and Stuttering

### ISSUE THREAD

**Issue by jmlumpkin** [aschober/vinyl-cast#3]
When running this, one thing that has been noticed is that the audio will play fine for a few seconds, and then silence, and maybe bits and pieces in between. 

It is able to determine what is playing. 

Is this an issue with streaming? What could be done?

**Comment by npitts5397** [comment]
This issue happens to me on every device I've tried except my Pixel 2 XL; even on devices that are only a couple years old, like my Nexus 6P.

**Comment by aschober** [comment]
I refactored the app to use better/faster/stronger native audio APIs using the Android Oboe library. Performance seems much improved on the different devices I'm able to test on (Pixel 3, Nexus 6, Nexus 5C).

Check out v1.0.0 in the Releases section and re-open an issue if you're still seeing problems.
