### ISSUE TITLE
What minimum Android version is needed?

### ISSUE THREAD

**Issue by MattWenham** [aschober/vinyl-cast#4]
What's the minimum version of Android that this will run on please?

**Comment by johnheroy** [comment]
It looks like Android 6.0 (Marshmallow) is the min version, though I'm not sure if the app could be adapted for lower versions as well:

https://github.com/aschober/vinyl-cast/blob/master/app/build.gradle#L19

**Comment by aschober** [comment]
Min is indeed API 23 (Android 6.0).

Closing issue.
