### ISSUE TITLE
Lossless audio

### ISSUE THREAD

**Issue by seibei-iguchi** [aschober/vinyl-cast#8]
Hello, this is an awesome project! I'm currently using Bluetooth transmitter to stream my turntable output to a wireless speaker (that supports Chromecast and AirPlay as well). Bluetooth has its limits when it comes to sound quality, so I am looking for a way to stream at the highest quality possible. Is there a reason the audio is converted to 16bit 192kbit AAC and not streamed in a lossless codec? By the way, I would connect my phone directly into https://www.project-audio.com/en/product/phono-box-ds2-usb/ which uses 48/96/192 kHz sampling. Would that work?

**Comment by seibei-iguchi** [comment]
Sorry, I haven't noticed the option to send WAV in the documentation. Anyway, it seems Android (and Google Cast) supports 24bit and up to 96kHz sample rate. Perhaps it could be added as an option?

**Comment by rotaryrkt** [comment]
Hi Adam,
Did you get connected with your DS2?  I'm using a Focusrite Scarlett interface, but the app does not recognize it.

**Comment by aschober** [comment]
Slow response, but the just released v1.1.0 (available in GitHub Releases) supports choosing between WAV (lossless) and AAC (lossy). Closing for now.
