### ISSUE TITLE
Wireless usb?

### ISSUE THREAD

**Issue by mrbougles** [aschober/vinyl-cast#9]
Could a wireless usb hub or a remote Android controller along with a 2nd Android device to use the app while away from the vinyl deck? Just a thought and wondred if you thought it was viable. 

https://www.net-usb.com/usb-over-wi-fi/

https://play.google.com/store/apps/details?id=com.teamviewer.teamviewer.market.mobile

**Comment by aschober** [comment]
@mrbougles good question.

I haven't explored / tried out any wireless usb options so can't comment there. 

If you have an extra Android device, definitely could leave it hooked up to your hifi setup and use a "remote desktop" type solution to control the Android device remotely. I've used [Vysor](https://www.vysor.io/) previously for remotely controlling an Android device from a PC/Mac and would recommend it.

If you were able to find something, I would be curious. Closing issue for now.
